#!/usr/bin/env python3
# coding=utf-8

import re, json, sys, getopt
from pprint import pprint
from doorlock import Doorlock
from urllib.parse import urlparse, parse_qs

from http.server import HTTPServer, BaseHTTPRequestHandler

def parseOptions(argv):
    options = {"dryRun": False, "port": 80}
    (opts, args) = getopt.getopt(argv[1:], "p:D", ["port=", "dry-run"])
    for (opt, value) in opts:
        if (opt == '-p' or opt == '--port'):
            options['port'] = int(value)
        elif (opt == '-D' or opt == '--dry-run'):
            options['dryRun'] = True
    return options

class Controller:
    def __init__(self, doorlock):
        self.doorlock = doorlock

    def jsonResponse(self, code, data):
        return {
            "code": code,
            "headers": [("Content-Type", "text/json; charset=utf-8")],
            "data": json.dumps(data)
        }

    def handleStatus(self, params):
        if not ('sid' in params):
            return self.jsonResponse(200, {"code": "invalid_sid"});
        return self.jsonResponse(200, self.doorlock.status(params['sid']))

    def handleOpen(self, params):
        if not ('sid' in params):
            return self.jsonResponse(200, {"code": "invalid_sid"});
        return self.jsonResponse(200, self.doorlock.open(params['sid']))
    
    def handleTick(self):
        self.doorlock.tick()

    def handleInvalid(self, params):
        return {
            "code": 404,
            "headers": [("Content-Type", "text/html; charset=utf-8")],
            "data": "<html><body><h1>Not Found</h1><p>File not found</p></body></html>"
        }
    def handleRequest(self, realPath, params):
        if (realPath == "/status"):
                fn = self.handleStatus
        elif (realPath == "/open"):
                fn = self.handleOpen
        else:
                fn = self.handleInvalid
        response = fn(params)
        return response

options = parseOptions(sys.argv)
doorlockObj = Doorlock(options['dryRun'])
controller = Controller(doorlockObj)

class MyHandler (BaseHTTPRequestHandler):
    def do_GET(self):
        url = urlparse("http://localhost"+self.path)
        realPath = url.path
        getParams = {}
        params = parse_qs(url.query, True)
        for p in params:
            getParams[p] = params[p][-1]
        
        response = controller.handleRequest(realPath, getParams)
        self.send_response(response["code"]);
        for h in response["headers"]:
                self.send_header(h[0], h[1])
        self.end_headers()
        self.wfile.write(bytes(response["data"], "utf-8"))

class MyHTTPServer (HTTPServer):
    def service_actions(self):
        super().service_actions()
        controller.handleTick()


#pprint(options)

httpd = MyHTTPServer(('',options['port']), MyHandler)
httpd.serve_forever(1)
