#!/usr/bin/env python3
# coding=utf-8

import re, json, sys, getopt
from pprint import pprint
from doorlock import Doorlock
from urllib.parse import urlparse, parse_qs

from http.server import HTTPServer, BaseHTTPRequestHandler

def parseOptions(argv):
    options = {"dryRun": False, "port": 80, "key": None}
    (opts, args) = getopt.getopt(argv[1:], "p:k:d", ["port=", "key=", "dry-run"])
    for (opt, value) in opts:
        if (opt == '-p' or opt == '--port'):
            options['port'] = int(value)
        elif (opt == '-d' or opt == '--dry-run'):
            options['dryRun'] = True
        elif (opt == '-k' or opt == '--key'):
            options['key'] = value
    return options

class Controller:
    def __init__(self, doorlock):
        self.doorlock = doorlock

    def jsonResponse(self, code, data):
        return {
            "code": code,
            "headers": [("Content-Type", "text/json; charset=utf-8")],
            "data": json.dumps(data)
        }

    def handleStatus(self, params):
        sid = None
        if ('sid' in params):
            sid = params['sid']
        return self.jsonResponse(200, self.doorlock.status(sid))

    def handleOpen(self, params):
        sid = None
        timeout = 5000
        if ('sid' in params):
            sid = params['sid']
        if ('timeout' in params):
            try:
                timeout = int(params['timeout'])
            except ValueError:
                return self.jsonResponse(200, {"error": "invalid_timeout"});
            
            if timeout <= 0:
                return self.jsonResponse(200, {"error": "invalid_timeout"});
            
        return self.jsonResponse(200, self.doorlock.open(sid, timeout))
    
    def handleTick(self):
        self.doorlock.tick()

    def handleInvalid(self, params):
        return {
            "code": 404,
            "headers": [("Content-Type", "text/html; charset=utf-8")],
            "data": "<html><body><h1>Not Found</h1><p>File not found</p></body></html>"
        }
    def handleRequest(self, realPath, params):
        if (realPath == "/status"):
                fn = self.handleStatus
        elif (realPath == "/open"):
                fn = self.handleOpen
        else:
                fn = self.handleInvalid
        response = fn(params)
        return response

options = parseOptions(sys.argv)
doorlockObj = Doorlock(options['dryRun'], options['key'])
controller = Controller(doorlockObj)

class MyHandler (BaseHTTPRequestHandler):
    def do_GET(self):
        url = urlparse("http://localhost"+self.path)
        realPath = url.path
        getParams = {}
        params = parse_qs(url.query, True)
        for p in params:
            getParams[p] = params[p][-1]
        
        response = controller.handleRequest(realPath, getParams)
        self.send_response(response["code"]);
        for h in response["headers"]:
                self.send_header(h[0], h[1])
        self.end_headers()
        self.wfile.write(bytes(response["data"], "utf-8"))

    def log_message(self, format, *args):
        pass


class MyHTTPServer (HTTPServer):
    def service_actions(self):
        super().service_actions()
        controller.handleTick()



httpd = MyHTTPServer(('',options['port']), MyHandler)
httpd.serve_forever(.1)
